from typing import Protocol
from app.models import ExerciseContent, EvaluationJudgments, LearnerProfile, Transcription

class AIProvider(Protocol):
    async def generate(self, profile: LearnerProfile) -> ExerciseContent: ...
    async def speech(self, exercise: ExerciseContent) -> bytes: ...
    async def transcribe(self, audio: bytes, filename: str) -> Transcription: ...
    async def evaluate(self, exercise: ExerciseContent, transcript: str) -> EvaluationJudgments: ...
