from typing import Protocol
from app.onboarding import ProfileExtraction
from app.models import ExerciseContent, EvaluationJudgments, LearnerProfile, Transcription, EvidenceAssessment, ConversationTurn

class AIProvider(Protocol):
    async def generate(self, profile: LearnerProfile) -> ExerciseContent: ...
    async def speech(self, exercise: ExerciseContent) -> bytes: ...
    async def transcribe(self, audio: bytes, filename: str) -> Transcription: ...
    async def evaluate(self, exercise: ExerciseContent, transcript: str) -> EvaluationJudgments: ...

    async def speak(self, text: str, speech_rate: float = .9) -> bytes: ...
    async def assess(self, exercise: ExerciseContent, turns: list[ConversationTurn]) -> EvidenceAssessment: ...

    async def extract_profile(self, stage: str, text: str) -> ProfileExtraction: ...
